In [5]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("COVID19_state.csv")
df.head(10)

,State,Tested,Infected,Deaths,Population,Pop Density,Gini,ICU Beds,Income,GDP,...,Hospitals,Health Spending,Pollution,Med-Large Airports,Temperature,Urban,Age 0-25,Age 26-54,Age 55+,School Closure Date
0,Alaska,7068,226,7.0,734002,1.2863,0.4081,119,59687,73205,...,21,11064,6.4,1.0,26.60,66.0,0.36,0.39,0.25,03/19/20
1,Alabama,18982,2499,67.0,4908621,96.9221,0.4847,1533,42334,45219,...,101,7281,8.1,1.0,62.80,59.0,0.33,0.37,0.31,03/16/20
2,Arkansas,14909,1077,18.0,3038999,58.4030,0.4719,732,42566,42454,...,88,7408,7.1,0.0,60.40,56.2,0.34,0.37,0.30,03/17/20
3,Arizona,34564,2726,80.0,7378494,64.9550,0.4713,1559,43650,48055,...,83,6452,9.7,1.0,60.30,89.8,0.33,0.36,0.30,03/16/20
4,California,168800,16957,442.0,39937489,256.3727,0.4899,7338,62586,74205,...,359,7549,12.8,9.0,59.40,95.0,0.33,0.40,0.26,03/19/20
5,Colorado,29199,5655,193.0,5845526,56.4011,0.4586,1597,56846,63882,...,89,6804,6.7,1.0,45.10,86.2,0.33,0.40,0.27,03/23/20
6,Connecticut,31700,8781,335.0,3563077,735.8689,0.4945,674,74561,76342,...,32,9859,7.2,1.0,49.00,88.0,0.30,0.38,0.32,03/17/20
7,District of Columbia,8283,1440,27.0,720687,11814.5410,0.5420,314,47285,200277,...,10,11944,9.8,0.0,54.65,100.0,0.30,0.48,0.22,03/16/20
8,Delaware,9439,1116,19.0,982895,504.3073,0.4522,186,51449,77253,...,7,10254,8.3,0.0,55.30,83.3,0.30,0.37,0.33,03/16/20
9,Florida,144570,15698,323.0,21992985,410.1256,0.4852,5604,49417,48318,...,217,8076,7.4,7.0,70.70,91.2,0.29,0.37,0.35,03/16/20

In [14]:
df['rate']=df['Infected']/df['Tested']

In [18]:
r_1 = np.corrcoef(df['rate'], df['Smoking Rate'])
r_1

array([[1.        , 0.05258096],
       [0.05258096, 1.        ]])

In [19]:
r_2 = np.corrcoef(df['rate'], df['Pollution'])
r_2

array([[ 1.        , -0.44300607],
       [-0.44300607,  1.        ]])

array([[1.       , 0.4561345],
       [0.4561345, 1.       ]])